#!/usr/bin/env python3
"""catches.py — the "Catches" page: earthquakes this station has actually recorded.

Presentation data, in the content.py style: no logic beyond assembling HTML. Each catch
is a dict; the images are static PNGs in dashboard/catches/, rendered from the archive
with analysis/quake_share.py (and shrunk to ~150 KB for the web). The detection-range
map is analysis/detection_map.py's output, copied here whenever the harvest CSV it
calibrates from is refreshed.

Why static images: the events are historical, the day-files live on the station and
pi5 (not on the public copy), and a share image is a considered artefact, not a live
render. Regenerate with:

    analysis/.venv/bin/python analysis/quake_share.py --mseed <day.mseed> \\
        --usgs-near <trigger time> --spectrogram --out dashboard/catches/<name>.png
    analysis/.venv/bin/python analysis/detection_map.py --out dashboard/catches/detection-range-map.png

The numbers are NOT hand-typed. `confirmed.json` (analysis/catches_data.py) carries every
confirmed event with the harvest's measurements and, where analysis/refstation_compare.py
has run, the amplitude ratio against USGS NP.1835 and the side-by-side figure
(`ref-<date>-<slug>.png`). The summary table, the stat strip on each featured catch and
the reference section all read from it; the prose in CATCHES is the commentary. Refresh:

    analysis/.venv/bin/python analysis/refstation_compare.py <origin> ... --harvest
    analysis/.venv/bin/python analysis/catches_data.py

Conventions follow content.py: HTML entities, "{place}" substituted by the caller.
"""
import json
import os

CATCH_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "catches")


def _confirmed():
    """Every confirmed event + headline numbers, from analysis/catches_data.py."""
    try:
        with open(os.path.join(CATCH_DIR, "confirmed.json")) as fh:
            d = json.load(fh)
        return d.get("summary", {}), d.get("events", [])
    except Exception:
        return {}, []


SUMMARY, EVENTS = _confirmed()
_BY_ORIGIN = {e["origin"][:19]: e for e in EVENTS}


def event_for(c):
    """The confirmed.json row behind a featured catch, matched on origin second."""
    return _BY_ORIGIN.get((c.get("origin") or "")[:19])


def card_id(c):
    """Anchor for a featured catch, so the table can link to it."""
    return "e-" + c["origin"][:16].replace(":", "").replace("T", "-")


def _fmt(v, nd=1, unit=""):
    if v is None:
        return "&mdash;"
    return f"{v:,.{nd}f}{unit}"


def _ref_cell(e):
    """The 'vs NP.1835' number with its honesty flags, or a dash."""
    r = e.get("ref")
    if not r:
        return '<span class="text-muted">&mdash;</span>'
    txt = f"{r['ratio_rms']:.2f}&times;"
    tip = "NP.1835 / this station, RMS in 5&ndash;15 Hz over the P/S window; 1.00 = calibration exact"
    if not r.get("ref_ok"):
        txt = f'<span class="text-muted">{txt}</span>'
        tip = "reference at its own noise floor &mdash; ratio not meaningful"
    if not r.get("amp_epoch_ok"):
        txt += "&nbsp;&dagger;"
    return f'<span title="{tip}">{txt}</span>'


AUDIO_DIR = os.path.join(CATCH_DIR, "audio")


def audio_path(name):
    """The pre-rendered clip for a catch image name, or None.

    Static, like the images and for the same reason: the public copy has no day-files,
    so anything this page needs is a committed artefact rather than a live read.
    Generated by analysis/catch_audio.py. Not every catch has one -- the St Helena M2.5
    of 2026-07-25 predates the owned archive, so it simply gets no button.
    """
    stem = os.path.basename(name).rsplit(".", 1)[0]
    if "/" in name or ".." in stem:
        return None
    p = os.path.join(AUDIO_DIR, stem + ".json")
    return p if os.path.exists(p) else None


def _ver(path):
    """Short version tag from a file's mtime+size, for cache-busting a URL.

    The image and its clip MUST agree: they share a time window, and a browser holding a
    cached clip beside a freshly rendered image would put the playhead in the wrong place
    -- precisely the misalignment this pairing exists to fix. Both are served with long
    cache headers (correct, they are static), so the URL has to change when the file does.
    """
    try:
        st = os.stat(path)
        return f"{int(st.st_mtime):x}{st.st_size:x}"[-8:]
    except OSError:
        return "0"


def _play_button(img):
    if not audio_path(img):
        return ""
    stem = img.rsplit(".", 1)[0]
    v = _ver(audio_path(img))
    return (f'<button class="cx-play" type="button" data-clip="{stem}" data-v="{v}">'
            f'<span>&#9654;</span> Hear this earthquake</button>'
            f'<span class="cx-note" data-note="{stem}"></span>'
            f'<div class="cx-wave" data-wave="{stem}">'
            f'<div class="cx-frame"><canvas></canvas>'
            f'<div class="cx-mark"><b>P</b></div>'
            f'<div class="cx-head"></div></div></div>')


def _map_stats():
    """Headline numbers written beside the map by analysis/detection_map.py.

    Not hand-maintained: this count went stale twice on 2026-09-02 alone -- the prose
    said 32 while the map's own legend said 33, then said 33 after the harvest moved to
    34. Anything derived from the calibration is read from the calibration.
    """
    try:
        with open(os.path.join(CATCH_DIR, "detection-range-map.json")) as fh:
            d = json.load(fh)
        return int(d["n_conf"]), float(d["reach_km"])
    except Exception:
        return None, None


_N_CONF, _REACH = _map_stats()
_N_TXT = f"{_N_CONF} of them" if _N_CONF else "all of them"
_REACH_TXT = f"{_REACH:g}&nbsp;km" if _REACH else "89&nbsp;km"

INTRO = (
    "<p>These are the earthquakes the station has recorded and that the USGS catalog "
    "confirms &mdash; magnitude, location, depth and origin time are the catalog&rsquo;s; "
    "the waveform, the peak and the timing are ours. A single geophone <em>detects</em>; "
    "a network <em>confirms</em>, and every event here was also recorded by professional "
    "stations, which is what makes it an earthquake and not a truck.</p>"
    "<p>Each image is the raw 1&ndash;15&nbsp;Hz trace with its smoothed envelope, and a "
    "spectrogram below it: an earthquake arrives as a burst that <em>starts</em> at low "
    "frequency and stays there, because the ground filters out the high frequencies on "
    "the way; a local disturbance is broadband and impulsive. That difference is how the "
    "detector tells them apart &mdash; though the Santa&nbsp;Rosa M1.8 below is the "
    "exception that proves it, because at 2.8&nbsp;km there is no path to do the "
    "filtering.</p>"
)

MAP_TEXT = (
    "<p>How far can a 4.5&nbsp;Hz geophone on a garage floor hear? The rings are the "
    "predicted reach by magnitude, inverted from the same amplitude model the harvester "
    "uses and corrected by what the confirmed catches actually measured. Three rings per "
    "magnitude: the inner is a noisy afternoon, the outer a quiet night. Dots are the "
    f"confirmed catches &mdash; {_N_TXT}, out to {_REACH_TXT}, and the dashed line is the "
    "furthest. Corrected for what those measured, the station reads about 1.8&times; quieter "
    "than the textbook California attenuation predicts.</p>"
    "<p>Two events sit outside that circle and are the only hard constraints on the far "
    "field. The X is an M3.4 at 348&nbsp;km that was looked for and not seen: it falls "
    "outside the median ring but inside the best-case one, so the miss says the best case is "
    "an upper bound rather than a promise. The diamond is the M4.8 off Petrolia at "
    "319&nbsp;km that <em>was</em> recorded (below) &mdash; identified by arrival time rather "
    "than amplitude, and deliberately left out of the fit, because it reads 16&times; below "
    "textbook and letting one far-field point in would reshape every ring on the map.</p>"
    "<p>Everything past the dashed line is extrapolation. Beyond ~150&nbsp;km what survives "
    "is low-frequency Lg energy, exactly where this geophone is deaf, so the outer rings "
    "are upper bounds. The map is regenerated whenever the catalog comparison is "
    "re-run.</p>"
)

# (image, headline, subtitle, facts-as-html-list-items)
CATCHES = [
    dict(
        img="2026-07-29-m4.2-cloverdale.png",
        origin="2026-07-29T02:40:06",
        head="M4.2 &middot; Cloverdale &middot; 2026-07-29",
        sub="02:40:06 UTC &middot; 38.777&deg;N 122.936&deg;W &middot; depth 5.9 km &middot; 46 km NW, on the Maacama fault",
        facts=[
            "<b>The biggest signal this station has recorded</b> &mdash; though no longer "
            "the biggest earthquake. Peak <b>1,406&nbsp;&micro;V</b> in 1&ndash;15&nbsp;Hz "
            "against a ~1.5&nbsp;&micro;V floor, an ~80&nbsp;s coda, and a detector ratio of "
            "8,535, where the previous record was 645. The M4.8 off Petrolia above is the larger "
            "quake &mdash; 0.6 magnitude units, about four times the amplitude at the "
            "source &mdash; and it arrived here at 52&nbsp;&micro;V, <b>27 times "
            "smaller</b>, because it happened 319&nbsp;km away instead of 46.",
            "Not remotely clipped: the whole event used ~3.5&nbsp;% of the digitizer&rsquo;s range.",
            "First arrival at <b>+9.06&nbsp;s</b>. That was 1.4&nbsp;s later than the textbook "
            "P-velocity predicted, and with four other events the same day it pinned the "
            "station&rsquo;s own crustal velocity at 5.19&nbsp;km/s &mdash; the number every "
            "prediction on this site now uses.",
            "Four more confirmed events the same day: three aftershocks at 46&nbsp;km and an M1.5 "
            "near Angwin at 29&nbsp;km.",
        ],
    ),
    dict(
        img="2026-08-13-san-leandro-m4.1.png",
        origin="2026-08-13T15:30:04",
        head="M3.8 &middot; San Leandro &middot; 2026-08-13",
        sub="15:30:04 UTC &middot; 37.755&deg;N 122.150&deg;W &middot; depth 5.5 km &middot; 88 km SSE, on the Hayward fault (first reported as M4.1)",
        facts=[
            "Still the <b>furthest catch inside the calibrated range</b> &mdash; 88&nbsp;km, "
            "nearly twice the previous record, and the event the map&rsquo;s dashed circle is "
            "drawn from. The M4.8 off Petrolia above was recorded nearly four times further "
            "out, but it reads so far below the textbook amplitude that it is deliberately "
            "left out of the fit, so this is where measurement still ends and inference "
            "begins. Peak 503&nbsp;&micro;V at +30&nbsp;s, the energy arriving as a long train "
            "of S and surface waves rather than a sharp onset &mdash; what 88&nbsp;km of crust "
            "does to a signal.",
            "The Hayward and Rodgers Creek faults are one connected system; this is the "
            "neighbour to the south announcing itself.",
            "A second event of M2.8 followed 37 minutes later and was recorded too. Both were "
            "used to calibrate this station against a USGS strong-motion instrument 1.6&nbsp;km "
            "away.",
        ],
    ),
    dict(
        img="2026-08-29-m4.8-petrolia.png",
        origin="2026-08-29T02:41:11",
        head="M4.8 &middot; off Petrolia &middot; 2026-08-29",
        sub="02:41:11.61 UTC &middot; 40.450&deg;N 125.272&deg;W &middot; depth 10 km &middot; "
            "319 km NW, offshore of the Mendocino triple junction",
        facts=[
            "The <b>furthest catch by a factor of 3.6</b> &mdash; 319&nbsp;km against a previous "
            "record of 89&nbsp;km. Peak 52&nbsp;&micro;V, signal-to-noise ~27&times;, and energy "
            "above twice the noise floor for <b>five minutes</b>.",
            "<b>Identified by the clock, not by amplitude.</b> Pn was due at 02:41:56.7 "
            "(iasp91, 319&nbsp;km, 10&nbsp;km deep) and the detector triggered at "
            "<b>02:41:57.0</b>; Sn was due at 02:42:32.1 and the envelope peaked at "
            "<b>02:42:31.7</b>. Two independent arrivals, each inside half a second. It is also "
            "the only catalogued event within 700&nbsp;km in a nine-minute window.",
            "<b>This is what 319&nbsp;km does to a signal.</b> In the spectrogram every bit of "
            "the energy sits below ~7&nbsp;Hz, hugging the geophone&rsquo;s own 4.5&nbsp;Hz "
            "corner &mdash; the crust has stripped everything above it out on the way. Its "
            "high/low band ratio is 0.40, where every other trigger that evening ran 1.2 to "
            "3.3. Set it beside the M1.8 below, which arrived from 2.8&nbsp;km with energy "
            "still present at 24&nbsp;Hz: same instrument, same night, opposite ends of the "
            "same rule.",
            "<b>The station said so at the time.</b> The trigger classifier scored it "
            "p&nbsp;=&nbsp;0.991 and pushed a notification 91&nbsp;s after the P arrival; the "
            "follow-on trigger 32&nbsp;s later scored 0.838 and was correctly swallowed by the "
            "five-minute hold-off, so one earthquake produced one alert.",
            "It is drawn on the range map above as a diamond but is <b>not part of the "
            "calibration</b>. It reads 16&times; below the textbook amplitude &mdash; past the "
            "cut the fit uses to throw out probable mis-associations &mdash; because what "
            "survives this far out is low-frequency Lg, the band a 4.5&nbsp;Hz geophone is "
            "built to reject. Fitting it would make one far-field point the anchor for every "
            "ring on the map.",
        ],
    ),
    dict(
        img="2026-08-29-m1.8-santa-rosa.png",
        origin="2026-08-29T00:42:16",
        head="M1.8 &middot; Santa Rosa &middot; 2026-08-29",
        sub="00:42:16.67 UTC &middot; 38.429&deg;N 122.633&deg;W &middot; depth 9.4 km &middot; "
            "2.8 km ESE &mdash; all but underneath the station",
        facts=[
            "The <b>closest catch</b>. 2.8&nbsp;km on the map, but 9.4&nbsp;km down, so the "
            "real distance is 9.9&nbsp;km and almost all of it is depth &mdash; this one arrived "
            "from below. Nothing catalogued had come within 8.4&nbsp;km of the station before "
            "that night.",
            "Peak <b>191&nbsp;&micro;V</b>, signal-to-noise ~67&times;, detector ratio 585 &mdash; "
            "from an <em>M1.8</em>. The M2.5 at 18&nbsp;km managed 117&nbsp;&micro;V and the M4.2 "
            "at 46&nbsp;km 1,406&nbsp;&micro;V: at this range distance matters far more than "
            "magnitude.",
            "<b>The high frequencies survived.</b> Every other catch here arrives low-frequency "
            "because kilometres of rock strip the highs out on the way. There is no such path "
            "here, and the spectrogram shows energy right up to ~24&nbsp;Hz at onset. This is the "
            "event that shows the rule is about the path, not about earthquakes.",
            "First motion <b>+1.47&nbsp;s</b> after origin &mdash; ~0.4&nbsp;s earlier than the "
            "station&rsquo;s 5.19&nbsp;km/s crustal velocity predicts. That figure was fitted to "
            "18&ndash;90&nbsp;km paths through shallow crust; this ray went almost straight up "
            "from 9.4&nbsp;km, through deeper and faster rock.",
            "It had an <b>aftershock, and that one was recorded too</b>: M1.38 at "
            "04:13:48&nbsp;UTC, 3&frac12; hours later and from the same 2.9&nbsp;km spot. "
            "Predicted P at 04:13:49.7, trigger at 04:13:50.0, peak 43.6&nbsp;&micro;V. The "
            "classifier gave it only p&nbsp;=&nbsp;0.13, though &mdash; a very local quake is "
            "broadband and impulsive, which is exactly what cultural noise looks like, and the "
            "model was trained on 19 positives that are mostly further away. Close events are "
            "its blind spot.",
            "It <b>should have sent a push notification and did not</b>. Re-scored afterwards the "
            "trigger classifier gives it <b>p&nbsp;=&nbsp;0.988</b>, comfortably past the 0.7 "
            "alert threshold &mdash; but the detector released the trigger before the last "
            "seconds of its scoring window had arrived from the station, so it was never scored "
            "and the alert never fired. Found and fixed the same day.",
        ],
    ),
    dict(
        img="2026-07-25-m2.5-st-helena.png",
        origin="2026-07-25T11:31:41",
        head="M2.5 &middot; St. Helena &middot; 2026-07-25",
        sub="11:31:41 UTC &middot; 38.507&deg;N 122.435&deg;W &middot; depth 6.2 km &middot; 18 km ENE, the Rodgers Creek / Maacama step-over",
        facts=[
            "<b>The first confirmed earthquake</b>, five days after the station moved to the "
            "garage. A clean, impulsive local event: sharp P at +3.97&nbsp;s, peak 117&nbsp;&micro;V, "
            "signal-to-noise ~85&times;.",
            "Close enough that P and S are only ~2.4&nbsp;s apart and merge into one burst &mdash; "
            "there is no independent S&ndash;P distance from one trace; the 18&nbsp;km is the "
            "catalog&rsquo;s.",
            "Also recorded by BK.CMB (broadband, 185&nbsp;km) and CE.68327 (Santa Rosa strong-"
            "motion). Their picks are what located it.",
        ],
    ),
    dict(
        img="2026-08-12-geysers-m3.2.png",
        origin="2026-08-12T10:28:21",
        head="M3.2 &middot; The Geysers &middot; 2026-08-12",
        sub="10:28:21 UTC &middot; 43 km NNW &middot; the geothermal field",
        facts=[
            "Peak 227&nbsp;&micro;V. The Geysers is the world&rsquo;s largest geothermal field and "
            "produces several small earthquakes a day, driven by the wastewater injected to "
            "recharge the steam reservoir &mdash; some of it Santa Rosa&rsquo;s own.",
            "That makes it a permanent calibration source 45&nbsp;km away: same path every "
            "time, a new event every few days.",
        ],
    ),
    dict(
        img="2026-08-11-geysers-m2.8.png",
        origin="2026-08-11T21:35:14",
        head="M2.8 &middot; The Geysers &middot; 2026-08-11",
        sub="21:35:14 UTC &middot; 45 km NNW",
        facts=[
            "Peak 159&nbsp;&micro;V. The workhorse event: its waveform was scaled and superposed "
            "onto recorded cultural noise to measure how much sensitivity the station loses "
            "while someone is dragging trash cans past it (about two thirds of a magnitude "
            "unit, as it turns out).",
            "Compared against the strong-motion station 1.6&nbsp;km away, it says this geophone "
            "reads about 3&times; quieter than its nameplate &mdash; the calibration now in use.",
        ],
    ),
    dict(
        img="2026-07-27-m2.5-the-geysers.png",
        origin="2026-07-27T06:29:25",
        head="M2.5 &middot; The Geysers &middot; 2026-07-27",
        sub="06:29:25 UTC &middot; 38.798&deg;N 122.781&deg;W &middot; depth 3.5 km &middot; 41 km NNW",
        facts=[
            "The second confirmed event, two days after the first, and the first from The "
            "Geysers. Onset at +8.15&nbsp;s &mdash; one of the five points that fixed the "
            "station&rsquo;s P velocity.",
        ],
    ),
    dict(
        img="2026-08-25-geysers-m2.4.png",
        origin="2026-08-25T00:22:31",
        head="M2.4 &middot; The Geysers &middot; 2026-08-25",
        sub="00:22:31 UTC &middot; 38.821&deg;N 122.843&deg;W &middot; depth 1.7 km &middot; 45 km NNW",
        facts=[
            "Peak 79&nbsp;&micro;V at 17:22 on a weekday afternoon, through the daytime traffic "
            "floor. The P onset landed on the predicted +9.0&nbsp;s to within a sample.",
            "Recorded with the station&rsquo;s original Python acquisition loop, a few hours "
            "before it was replaced by the C reader that now owns the digitizer.",
        ],
    ),
    dict(
        img="2026-09-02-m2.6-middletown.png",
        origin="2026-09-02T03:49:01",
        head="M2.6 &middot; Middletown &middot; 2026-09-02",
        sub="03:49:01 UTC &middot; 38.770&deg;N 122.612&deg;W &middot; depth 4.2 km &middot; "
            "35 km due north, in the Collayomi Valley &mdash; a patch of crust new to this station",
        facts=[
            "<b>People felt this one.</b> The USGS &ldquo;Did You Feel It?&rdquo; intensity "
            "came back as <b>MMI&nbsp;II</b> &mdash; the bottom of the felt scale, the "
            "kind you notice only if you are sitting still indoors. That is the "
            "interesting part: at M2.6 and 35&nbsp;km this sits right at the threshold "
            "where an earthquake stops being purely an instrumental event, and it is a "
            "usable data point for the question of whether an alert should say "
            "&ldquo;probably felt&rdquo; rather than quoting a detector ratio at you.",
            "<b>Not The Geysers</b>, which is where most of our catalogue comes from. The "
            "geothermal field lies 15.6&nbsp;km WNW of this epicentre, at bearing "
            "339&deg; from the station; this arrived at bearing <b>1.3&deg;</b>, almost due "
            "north. Of the ~990 catalogued events between 30 and 50&nbsp;km, 849 are Geysers "
            "or Cobb induced seismicity inside a narrow 335&ndash;350&deg; band. This is a "
            "different patch of crust &mdash; the Collayomi fault zone, tectonic rather than "
            "steam-field &mdash; and it is <b>the first one we have caught from it</b>: four "
            "earlier Middletown events, M0.46 to M1.52, all went past unrecorded.",
            "<b>The station&rsquo;s own velocity model beat the global one.</b> P broke out of "
            "the noise at <b>+7.14&nbsp;s</b>. Our locally measured 5.19&nbsp;km/s relation "
            "predicted +7.18&nbsp;s &mdash; wrong by 0.04&nbsp;s. iasp91, the global average "
            "used past 15&nbsp;km, said +6.10&nbsp;s, a full second early. At local distances "
            "the crust under Sonoma County is genuinely slower than the world average, which "
            "is exactly why that measurement was worth making.",
            "<b>The classifier had a good night.</b> The detector fired 17 times in the 11 "
            "minutes around this event. Its neighbours scored p(quake) between 0.002 and "
            "0.016; this one scored <b>0.999</b> and pushed an alert. Its high/low band ratio "
            "was 0.31 where the surrounding triggers ran 1.7 to 6.9.",
            "<b>What 35&nbsp;km does to a signal &mdash; compare it with Petrolia below.</b> "
            "The spectrogram here carries energy right up past 20&nbsp;Hz, because there is "
            "barely enough crust in the way to filter anything out. The M4.8 at 319&nbsp;km is "
            "a far bigger earthquake and arrives with nothing above ~7&nbsp;Hz. Same "
            "instrument, same summer; the difference is entirely the path.",
            "Peak <b>73&nbsp;&micro;V</b> in 1&ndash;15&nbsp;Hz, SNR ~46&times;, detector "
            "ratio 116.",
        ],
    ),
]



# Newest first. The image names start with the event date, so the filename IS the sort
# key -- add a catch anywhere in the list above and it lands in the right place.
CATCHES.sort(key=lambda c: c["img"], reverse=True)


def image_path(name):
    """Static image under dashboard/catches/, or None if the name is not one of ours."""
    if not name or "/" in name or not name.endswith(".png"):
        return None
    p = os.path.join(CATCH_DIR, name)
    return p if os.path.isfile(p) else None


_FEATURED = {c["origin"][:19]: c for c in CATCHES}

TABLE_TEXT = (
    "<p>Every event the catalog comparison confirms, newest first &mdash; the same list "
    "the map is calibrated from, so the two cannot disagree. Nothing here needs the "
    "detector to have fired: the catalog gives the time and the archive is cut there "
    "afterwards, which is how the weak ones get in. <b>Peak</b> is the maximum of the "
    "1&nbsp;s-smoothed 1&ndash;15&nbsp;Hz envelope in the P/S window, so it reads below the "
    "raw sample peaks quoted in the write-ups; <b>SNR</b> is that peak over the RMS of the "
    "minute before; <b>P pred.</b> is the predicted P arrival after origin. "
    "<b>vs&nbsp;NP.1835</b> is the amplitude "
    "ratio against the USGS strong-motion station 1.64&nbsp;km away, explained in the next "
    "section; 1.00 means the calibration is exact. Bold rows have a write-up below. The "
    "list starts at the 100&nbsp;sps cutover of 2026-07-25, so the first catch, the M2.5 "
    "St.&nbsp;Helena a few hours before it, has a write-up but no row.</p>"
)

_TH = ("<thead><tr><th>UTC</th><th>M</th><th>place</th><th class=\"text-end\">km</th>"
       "<th class=\"text-end\">depth</th><th class=\"text-end\">peak &micro;V</th>"
       "<th class=\"text-end\">SNR</th><th class=\"text-end\">P pred.</th>"
       "<th class=\"text-end\">vs NP.1835</th></tr></thead>")


def _table_row(e):
    key = e["origin"][:19]
    feat = _FEATURED.get(key)
    when = e["origin"][:16].replace("T", "&nbsp;")
    place = e["place"].replace(", CA", "")
    if feat:
        place = f'<a href="#{card_id(feat)}"><b>{place}</b></a>'
    if not e.get("in_fit", True):
        place += ' <span class="badge badge-quiet" title="recorded, but kept out of the range fit">not in fit</span>'
    return (f"<tr><td class=\"text-nowrap\">{when}</td><td>{_fmt(e['mag'], 1)}</td><td>{place}</td>"
            f"<td class=\"text-end\">{_fmt(e['dist_km'], 0)}</td>"
            f"<td class=\"text-end\">{_fmt(e['depth_km'], 1)}</td>"
            f"<td class=\"text-end\">{_fmt(e['peak_uv'], 0)}</td>"
            f"<td class=\"text-end\">{_fmt(e['snr'], 0)}</td>"
            f"<td class=\"text-end\">{_fmt(e['tp_s'], 1, '&nbsp;s')}</td>"
            f"<td class=\"text-end\">{_ref_cell(e)}</td></tr>")


def table_html():
    if not EVENTS:
        return TABLE_TEXT + '<p class="text-muted">confirmed.json not built yet.</p>'
    rows = "".join(_table_row(e) for e in EVENTS)
    foot = ("<p class=\"text-muted small mt-2 mb-0\">&dagger; recorded with the earlier "
            "front end (before the 2026-08-07 rebuild): a different amplitude epoch from "
            "the calibration anchors, shown but not averaged.</p>")
    return (TABLE_TEXT + '<div class="table-responsive"><table class="table table-sm '
            f'table-striped mb-0 align-middle">{_TH}<tbody>{rows}</tbody></table></div>' + foot)


def ref_text():
    """The reference-station section: method and the headline residual."""
    s = SUMMARY
    head = ""
    if s.get("ref_median") is not None:
        head = (f"<p><b>Result so far:</b> over the {s['n_ref']} confirmed events the reference "
                f"could see clearly, the residual ratio has a median of <b>{s['ref_median']:.2f}&times;</b> "
                f"(range {s['ref_min']:.2f}&ndash;{s['ref_max']:.2f}), so the 3.2&times; correction "
                "in use is right to within the site scatter two stations 1.64&nbsp;km apart "
                "are entitled to. The spread is the interesting part: at 5&ndash;15&nbsp;Hz two "
                "sites that close routinely differ by 2&times; on the same event, and which way "
                "depends on the path.</p>")
    return (
        "<p>NP.1835 is a USGS National Strong-Motion Project accelerometer at Santa Rosa "
        "Fire Station 7, <b>1.64&nbsp;km</b> from this geophone, whose waveforms and full "
        "instrument response the Northern California Earthquake Data Center serves "
        "publicly. Same basin, same geology, same earthquakes: it is as good a reference "
        "as this project will ever have, and every absolute number this station reports "
        "is anchored to it.</p>"
        "<p>The method is a direct waveform comparison. The reference&rsquo;s response is "
        "removed to ground velocity; our counts are converted with the <b>provisional "
        "sensitivity of 9.0&nbsp;V/(m/s)</b> that this same comparison produced (the "
        "nameplate says 28.8, and is wrong by 3.2&times;); both are band-passed to "
        "5&ndash;15&nbsp;Hz, above the geophone&rsquo;s 4.5&nbsp;Hz corner where its response is "
        "flat and nothing has to be modelled on our side. If the calibration is right the "
        "two traces lie on top of each other and the ratio printed on each figure is 1.0. "
        "Each featured catch below carries its own side-by-side figure.</p>"
        + head +
        "<p>Two honesty flags. A strong-motion accelerometer is deaf where a geophone is "
        "comfortable: below its own noise floor the ratio is meaningless and is greyed out "
        "in the table &mdash; though the figure is still worth a look, because a "
        "professional instrument measuring itself while this one records an earthquake "
        "at 60&times; signal-to-noise is rather the point of a sensitivity-first design. And "
        "events before the 2026-08-07 front-end rebuild are a different amplitude epoch, "
        "marked &dagger;: shown, never averaged.</p>"
    )


# (label, confirmed.json field, decimals, unit) -- the same strip on every featured catch
_STATS = [("magnitude", "mag", 1, ""), ("distance", "dist_km", 1, " km"),
          ("depth", "depth_km", 1, " km"), ("envelope peak", "peak_uv", 0, " µV"),
          ("envelope SNR", "snr", 0, "×"), ("P predicted", "tp_s", 1, " s"),
          ("sustain", "sustain_s", 1, " s"), ("low/high band", "lo_hi", 1, "×")]


def _stat_strip(e):
    """The same measurements on every featured catch, from the harvest -- so the
    numbers are comparable across cards, where the prose peaks (raw samples) are not."""
    if not e:
        return ""
    cells = "".join(f"<div><dt>{lab}</dt><dd>{_fmt(e.get(f), nd, unit)}</dd></div>"
                    for lab, f, nd, unit in _STATS)
    cells += f"<div><dt>vs NP.1835</dt><dd>{_ref_cell(e)}</dd></div>"
    return f'<dl class="stat-grid">{cells}</dl>'


def _ref_figure(e):
    r = (e or {}).get("ref") or {}
    img = r.get("img")
    if not img or not image_path(img):
        return ""
    cap = "Side by side with USGS NP.1835, 1.64&nbsp;km away, both in ground velocity."
    if not r.get("ref_ok"):
        cap += " The reference is at its own noise floor here."
    if not r.get("amp_epoch_ok"):
        cap += " Earlier front end than the calibration anchors, so the ratio is not averaged in."
    return (f'<img src="/catches/{img}" class="plot mt-3" loading="lazy" '
            f'alt="{e["place"]} against NP.1835">'
            f'<p class="text-muted small mt-2 mb-0">{cap}</p>')


def catch_html(c):
    e = event_for(c)
    facts = "".join(f"<li>{f}</li>" for f in c["facts"])
    return (
        f'<p class="text-muted small mb-2">{c["sub"]}</p>'
        + _stat_strip(e) +
        f'<img src="/catches/{c["img"]}?v={_ver(os.path.join(CATCH_DIR, c["img"]))}" '
        f'class="plot" loading="lazy" alt="{c["head"]}">'
        + _play_button(c["img"]) +
        f'<ul class="mt-3 mb-0">{facts}</ul>'
        + _ref_figure(e)
    )


# Drives the shared engine (listen.py) from a pre-rendered clip. No buffering: the whole
# clip is present, which removes the only fiddly part of the live version. Only one may
# sound at a time -- the engine enforces that, and this resets whichever button was last
# pressed so the page never shows two "playing" states.
CATCH_AUDIO_JS = """<script>
(function(){
  const btns=[...document.querySelectorAll('.cx-play')];
  if(!btns.length||!window.SeismoSynth) return;
  let active=null;
  const note=st=>document.querySelector('[data-note="'+st+'"]');
  const wave=st=>document.querySelector('[data-wave="'+st+'"]');

  // The waveform is drawn from the SAME samples the synth is playing, so the playhead
  // cannot drift from the sound. Drawing it here rather than overlaying the PNG also
  // sidesteps the fact that the two cover different time windows -- and it inherits the
  // page's theme tokens for free.
  function draw(box,clip){
    // Inset the frame to the axes box of the image above, which the clip carries with
    // it. Same window, same box, so the same x is the same instant in both -- which is
    // the whole point of the playhead being here rather than being decoration.
    const fr=box.querySelector('.cx-frame');
    if(clip.ax_x0!=null){
      fr.style.left=(clip.ax_x0*100).toFixed(3)+'%';
      fr.style.right=((1-clip.ax_x1)*100).toFixed(3)+'%';
    }
    const cv=box.querySelector('canvas');
    const w=fr.clientWidth, h=fr.clientHeight, dpr=window.devicePixelRatio||1;
    cv.width=w*dpr; cv.height=h*dpr;
    const g=cv.getContext('2d'); g.scale(dpr,dpr); g.clearRect(0,0,w,h);
    const cs=getComputedStyle(document.documentElement);
    g.strokeStyle=(cs.getPropertyValue('--ink-dim')||'#888').trim();
    g.lineWidth=1;
    const uv=clip.uv, n=uv.length;
    let peak=0; for(let i=0;i<n;i++){const a=Math.abs(uv[i]); if(a>peak)peak=a;}
    peak=peak||1;
    // one min/max column per pixel: honest at any width, and cheap
    g.beginPath();
    for(let x=0;x<w;x++){
      const i0=Math.floor(x*n/w), i1=Math.max(i0+1,Math.floor((x+1)*n/w));
      let lo=Infinity,hi=-Infinity;
      for(let i=i0;i<i1&&i<n;i++){ const v=uv[i]; if(v<lo)lo=v; if(v>hi)hi=v; }
      if(lo===Infinity) continue;
      const y0=h/2-(hi/peak)*(h/2-2), y1=h/2-(lo/peak)*(h/2-2);
      g.moveTo(x+0.5,y0); g.lineTo(x+0.5,y1);
    }
    g.stroke();
    // the P marker sits where the MEASURED pick sits, carried in the clip
    const mark=box.querySelector('.cx-mark');
    const frac=(clip.p_frac!=null) ? clip.p_frac
             : (clip.pre_s||0)/(n/(clip.fs||100));
    if(mark) mark.style.left=(frac*100).toFixed(3)+'%';
    return peak;
  }

  function reset(b){ if(!b) return; b.disabled=false;
    b.innerHTML='<span>&#9654;</span> Hear this earthquake';
    const st=b.dataset.clip, n=note(st), w=wave(st);
    if(n) n.textContent=''; if(w){ w.classList.remove('on'); }
  }

  btns.forEach(b=>b.addEventListener('click',async()=>{
    const stem=b.dataset.clip;
    if(active===b){ window.SeismoSynth.stop(); return; }
    reset(active); active=b;
    b.disabled=true; b.innerHTML='<span>&#9654;</span> loading…';
    try{
      const clip=await (await fetch('/catches/audio/'+stem+'.json?v='+(b.dataset.v||'0'))).json();
      const box=wave(stem), head=box?box.querySelector('.cx-head'):null;
      if(box){ box.classList.add('on'); draw(box,clip); }
      b.innerHTML='<span>&#9632;</span> Stop'; b.disabled=false;
      await window.SeismoSynth.start({
        clip,
        say:s=>{const n=note(stem); if(n) n.textContent=s;},
        onProgress:f=>{ if(head) head.style.left=(f*100).toFixed(2)+'%'; },
        onEnd:()=>{ reset(b); if(active===b) active=null; }
      });
    }catch(e){ const n=note(stem); if(n) n.textContent='could not load'; reset(b); }
  }));
})();
</script>"""
